# Cloud Build configuration for promoting images from dev to prod
steps:
  # Pull the source image from dev project
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/rate-grid-d/rate-grid-dev:$COMMIT_SHA
        docker tag gcr.io/rate-grid-d/rate-grid-dev:$COMMIT_SHA gcr.io/$PROJECT_ID/rate-grid:$COMMIT_SHA

  # Push the promoted image to prod project
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rate-grid:$COMMIT_SHA']

  # Deploy to Cloud Run in prod project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rate-grid:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,APP_ENV=production,GCP_PROJECT_ID=rate-grid'

  # Send build notification
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud pubsub topics publish ci-notify \
          --message="Image promotion completed for commit $COMMIT_SHA" \
          --attribute="status=success,environment=production,commit=$COMMIT_SHA"

images:
  - 'gcr.io/$PROJECT_ID/rate-grid:$COMMIT_SHA'

substitutions:
  _SERVICE_NAME: 'rate-grid'
  _REGION: 'us-central1'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# IAM Requirements:
# - Cloud Build Service Account needs:
#   - roles/run.admin on rate-grid project
#   - roles/storage.admin on rate-grid project
#   - roles/pubsub.publisher on ci-notify topic
# - Manual approval required via IAM condition:
#   - resource.type == "cloudbuild.googleapis.com/Build"
#   - resource.name.startsWith("projects/rate-grid/triggers/production-deploy") 