createTime: '2025-03-02T13:40:49.702205300Z'
description: Build and deploy to Cloud Run service rate-grid on push to "^main$"
filename: cloudbuild.yaml
github:
  name: rate-grid
  owner: rategrid
  push:
    branch: ^main$
id: 86027aa7-4cd5-44e7-9701-f48deb7bf81b
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: rate-grid
resourceName: projects/rate-grid/locations/global/triggers/86027aa7-4cd5-44e7-9701-f48deb7bf81b
serviceAccount: projects/rate-grid/serviceAccounts/256468121098-compute@developer.gserviceaccount.com
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_PROJECT_ID: rate-grid
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: us-central1
  _PLATFORM: managed
  _SERVICE_NAME: rate-grid
  _TRIGGER_ID: 86027aa7-4cd5-44e7-9701-f48deb7bf81b
tags:
- gcp-cloud-build-deploy-cloud-run
- gcp-cloud-build-deploy-cloud-run-managed
- rate-grid
