# IAM Requirements (managed by Terraform):
# - Cloud Build Service Account needs:
#   - roles/storage.admin on roastah project
#   - roles/pubsub.publisher on ci-notify topic
#
# All IAM permissions are now managed by Terraform 